### PR TITLE
Backport of JAVAMONEY-160

### PR DESCRIPTION
**Pull request by lukasniemeier-zalando**
See https://github.com/JavaMoney/jsr354-ri/commit/12bb383699a72aae8f8e1e23ba3c55ff3f3c6278

---
This change is [Reviewable](https://reviewable.io/reviews/javamoney/jsr354-ri-bp/36)

### CODE REVIEW

**Comment by lukasniemeier-zalando** [comment]
FYI on `master` my build is succeeding but signals failing tests
```
Failed tests:                                                                                                                                                                                                 
  IMFRateProviderTest.shouldConvertsBrazilianToDollar:132 » CurrencyConversion C...                                                                                                        
  IMFRateProviderTest.shouldConvertsDollarToBrazilian:145 » CurrencyConversion C...                                                                                                                           
  IMFRateProviderTest.shouldConvertsDollarToEuro:106 » CurrencyConversion Cannot...                                                                                                                           
  IMFRateProviderTest.shouldConvertsEuroToDollar:119 » CurrencyConversion Cannot...                                                                                                                           
                                                                                                                                                                                                              
Tests run: 452, Failures: 4, Errors: 0, Skipped: 0                                                                                                                                                            
                                                                                                                                                                                                     
[ERROR] There are test failures.     
```

**Comment by keilw** [comment]
The Travis build claims it passed. Won't merge now, but try later this evening. Thanks.

**Comment by keilw** [comment]
Please note, the BP currently is not modularized. As this is sort of a Jigsaw ease preparation in Moneta, if there is no negative side-effect, the BP might stay that way.

**Comment by lukasniemeier-zalando** [comment]
Any update? Do you miss something from me?

**Comment by keilw** [comment]
I believe this one could be OK, but there are a couple of other issues (mostly in Moneta, but BP also partly affected) we must resolve before a new build makes sense.

**Comment by keilw** [comment]
@lukasniemeier-zalando Any news on the JCP Associate Membership?

**Pull request merged**
