### PR TITLE
Make Modules in Moneta. 

### PR DESCRIPTION
**Pull request by otaviojava**
Initially, it was splitted in @keilw branch so, there are:

- moneta-core
- moneta-convert(base, IMF, ECB)
- moneta

### CODE REVIEW

**Comment by keilw** [comment]
Looks like it left quite a mess in https://oss.jfrog.org/artifactory/oss-snapshot-local/org/javamoney/moneta/, all "moneta-bp" artifacts should have gone to https://oss.jfrog.org/artifactory/oss-snapshot-local/org/javamoney/moneta-bp/ instead. Please check it out (might do later myself) and then we could have a PR here and in Moneta, too.

**Comment by otaviojava** [comment]
Werner, unfortunately. I did not find.
If you can do it, do it, please.

**Comment by otaviojava** [comment]
@keilw , could you fix the artefact in the pom , please.

**Comment by keilw** [comment]
Have you not been able to change it?

**Pull request closed without merging**
