### PR TITLE
Modules 1 2

### PR DESCRIPTION
**Pull request by keilw**

### CODE REVIEW

**Comment by keilw** [comment]
Only fixes to POM

**Comment by otaviojava** [comment]
Thanks @keilw I did the test and its look ok. I'll open the PR again, but I wait two weeks to more feedback.

**Comment by keilw** [comment]
If there are no pending changes in master that should be OK, otherwise the person performing a change should try to merge this first.

**Comment by otaviojava** [comment]
Yes, I did. I gonna do more test today and then I'll merge it.

**Comment by keilw** [comment]
Please let others (@atsticks, myself or whoever is willing to help) review it first.

**Comment by keilw** [comment]
Looks like this cannot be merged without conflicts any more. @otaviojava Please file another one if possible.

**Pull request closed without merging**
