### PR TITLE
Multiplication error fix and additional tests for the add method of FastMoney

### PR DESCRIPTION
**Pull request by joe-bookwood**

### CODE REVIEW

**Comment by otaviojava** [comment]
Thanks for your contribution.
Could you put this PR on RI too?
https://github.com/JavaMoney/jsr354-ri

Thanks

**Comment by joe-bookwood** [comment]
We don't need to put this PR to RI, because RI uses the new Java 8 Math.multiplyExact method.  

Please tell me when you plan to deploy a new release with this fix to maven central.

**Comment by otaviojava** [comment]
Thanks.

**Comment by keilw** [comment]
In Moneta-BP there needs to be an equivalent to multiplyExact!

**Comment by joe-bookwood** [comment]
@keilw my fix repair the multiplyExact equivalent method, because this method does not exist Java 7. If you multiply x with zero you got x and not zero, if you use the current version 1.0 or 1.1 from maven central. This is the error.

**Pull request merged**
